mySet = {1, 2, 3, 4, 5}
print(mySet)
mySet.add(6)
print(mySet)
mySet.pop()
print(mySet)
mySet.remove(3)
print(mySet)
mySet.discard(3)
print(mySet)
mySet2 = mySet.copy()
mySet.clear()
print(mySet)
print(mySet2)
